Urban-Analytics/RAMP-UA

.Rhistory, R/py_int/covid_run.R, R/py_int/covid_status_functions.R, R/py_int/initialize_and_helper_functions.R
this code should be working now. you should be able to source the covid_run.R script and then call the function run_status(pop), where pop is the population dataframe and it should return a dataframe with columns that we need to keep track of which are MSOA, PID, HID, disease_status, number of presymp days, and number of symptomatic days
=> working code

R/py_int/covid_run.R, R/py_int/covid_run_py.R, R/py_int/covid_status_functions.R
Reverts Urban-Analytics/RAMP-UA#42
=> Revert "Fiona"

microsim/column_names.py, microsim/microsim_model.py, model_parameters/default.yml, tests/test_microsim_model.py
Implemented hazard multipliers for disease types and locations https://github.com/Urban-Analytics/RAMP-UA/issues/87
=> Infect multiplier

.github/workflows/pythontesting.yml, .gitignore, README.md, environment.yml, microsim/activity_location.py, microsim/microsim_model.py, microsim/r_interface.py, setup.py, tests/test_dashboard.py
This is a series of commits that addresses #107 
This process updates the environment setup workflow, so i've updated the README.md to include new instructions.
To make sure everyones development environments are aligned i'd encourage people to delete their existing conda environments and create a new one from the updated environment.yml, run the setup.py develop command and run pytest locally, followed by running the microsim.
=> Fix #107 - import errors

microsim/dashboard.py, microsim/dashboard_QUANT.py, microsim/microsim_model.py, microsim/quant_api.py, model_parameters/default.yml
QUANTRampAPI2.py has been replaced by quant_api.py which defines the QuantRampAPI class. In microsim_model.py, a quant_dir parameter (added to default.yml) points to the QUANT files (relative path starting from data_dir). This is used to create a quant_object which is passed on to every Microsim object (they all get the same input, so the data only needs reading in once). _It looks like it's creating the right flow matrices, but someone may want to double check the output, since my computer doesn't manage the full version for QUANT and the R code at the same time._
dashboard.py and dashboard_QUANT.py have been updated (calculate and show standard deviation in scenario comparison plots). The files are now identical for easier maintenace except for 2 sections where either the Devon or QUANT …
=> Quant class and extended dashboard

.github/workflows/tagged-release.yml, README.md, setup.py
- updated version in setup.py
- included release instructions in readme
=> added tagged-release github action for automated release creation

devon_data/caches/.gitignore, devon_data/caches/README.md, microsim/microsim_model.py, tests/test_microsim_model.py
Cached workplaces so they don't have to be recalculated. For https://github.com/Urban-Analytics/RAMP-UA/issues/142
=> cache workplaces https://github.com/Urban-Analytics/RAMP-UA/issues/142

.github/issue-branch.yml, .github/workflows/issue-branch.yml
Nick this should do roughly what you're after I think.
Once someone is assigned to an issue this action automatically creates a new branch called `{assignee}-issue-{issue_no}-{issue_title}`
It should work once merged into master.
=> Add issue workflow

setup.py
bumping version number in setup.py for v1.0.0
=> bump version number for v1.0.0

setup.py
recent merges from @rory-improbable on obesity and lognormal implementation to opencl model, plus some bug fixes mean an increment to our package version
=> bumping version number

microsim/microsim_model.py, microsim/population_initialisation.py, tests/test_microsim_model.py, tests/test_population_initialisation.py
Each microsim model should have its own random number generator, so this needed to be in Microsim.
=> Moved random number generator from PopulationInitialisation to Microsim

R/py_int/covid_run.R
Added function which calculates someones risk of being symptomatic based on their age.
Values based on Fig 3a in this paper - https://www.nature.com/articles/s41591-020-0962-9#Fig1
Individuals under 20 have 0.21 chance of being symptomatic
Individuals over 70 have 0.69 change of being symptomatic.
There are no values given for the years in between so have linearly interpolated these. For each year of age between 20 and 70 your risk of being symptomatic increases by 0.009.
Obese individuals have their symptomatic risk multiplied by 1.46, so an obese 70 year old would have a 0.876 chance of being symptomatic.
=> symptomatic risk function working

MANIFEST.in
Opening this to check tests still pass.
=> added init files and manifest to ensure correct files captured in sdist

.codecov.yml
some files can be ignore from coverage reporting
=> added a codecov config file

setup.py
Changes in the OpenCL seeding logic (#194)  and other small changes (#192 #193) constitute a minor version number increment
=> bump version number for v1.2.0

.github/workflows/deploy-docs.yml
This is a quick update on master to the github actions for building the documentation. It was initially created to run on changes to the contents of the docs folder, but this hasn't triggered because there aren't often changes to the docs. For now i'll set it to run whenever there is just a push to master as it will fetch and update existing module docs based on doc strings.
However if we ever add new modules i'll need to do some manual changes to files in docs folder to make sure the docstrings are imported.
=> adjusted GHA for docs

.github/issue-branch.yml
this will now just create a branch name that is assignee-issueNumber
=> fixes #155 the long branch names created by the GHA issue brancher

.github/workflows/deploy-docs.yml
=> corrected doc build to install package

docs/source/contributing/docs.rst, docs/source/contributing/getting_started.rst, docs/source/contributing/index.rst, docs/source/contributing/model.rst, docs/source/index.rst
Adding some additional documentation specifically around contributing to the code base. As part of a general push to add more documentation
=> Update contributing docs

docs/source/dev_guide/index.rst, docs/source/index.rst
This PR:
- renamed "overview" to "developers guide" for https://github.com/Urban-Analytics/RAMP-UA/issues/259 (in branch https://github.com/Urban-Analytics/RAMP-UA/tree/nickmalleson-issue-259 )
- Linked directly to function and class documentation in for https://github.com/Urban-Analytics/RAMP-UA/issues/258
=>  Minor improvements to the developers guide

microsim/utilities.py
Using example from here: https://gist.github.com/wy193777/0e2a4932e81afc6aa4c8f7a2984f34e2
=> added progress bar

microsim/quant_api.py
I've gone through [quant_api.py](https://github.com/Urban-Analytics/RAMP-UA/blob/master/microsim/quant_api.py) file to tidy up docstrings into the sphinx format and add more spacing for readability.
=> a tidy up of the docstrings in quant_api

.github/workflows/tagged-release.yml, setup.py
We haven't had a version increase for some time, although we have introduced a number of changes to the model. Therefore, i'm incrementing the latest tag to create a new release that captures these changes.
=> bump version number for v1.4.0

docs/source/usage/r_disease_model.rst
Merging in @spoonerf's R documentation page
=> merging R documentation into this large documentation update branch

microsim/main.py
One-line fix for an issue  https://github.com/Urban-Analytics/RAMP-UA/issues/291 . All I did was remove a string concatenatoin for a directory and replaced it with `os.path.join`
=> Issue 291 

docs/source/Reference/microsim.rst, docs/source/usage/r_disease_model.rst, microsim/microsim_initialisation.py, microsim/microsim_model.py, microsim/population_initialisation.py
This pull request includes a number of updates to the Sphinx documentation page including:
- @spoonerf's documentation of the `rampuaR` package and its model logic
- Tidy up of docstrings in microsim modules
- Corrections to reduce Sphinx warnings
=> Documentation update
